name: Build Windows EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies (Windows)
        run: pip install -r requirements-win.txt

      - name: Clean previous builds
        run: |
          if (Test-Path build) { Remove-Item -Recurse -Force build }
          if (Test-Path dist) { Remove-Item -Recurse -Force dist }
          if (Test-Path IMU_Monitor.spec) { Remove-Item -Force IMU_Monitor.spec }

      - name: Build onefile EXE with PyInstaller
        run: |
          pyinstaller --noconfirm --clean `
            --name IMU_Monitor `
            --windowed `
            --onefile `
            main.py

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: IMU_Monitor-windows-exe
          path: dist/IMU_Monitor.exe
          if-no-files-found: error


